### ISSUE TITLE
Demo app crashed

### ISSUE THREAD

**Issue by loxyz-tw** [getbouncer/cardscan-android#223]
1.
The values of bouncerViewFinderVerticalBias and bouncerViewFinderHorizontalBias in dimensions.xml [scan-ui] should be 0.5, not 50.0%, since the values are used in a ConstraintLayout in activity_single_demo.xml.
Not sure if these values are used in other place.

2.
In SingleActivityDemo.java, line 392: "%s\n%s\n%d/%d\n%s\n%s", the %d/%d should be %s/%s, because the arguments below are all strings. 

(1)
Process: com.getbouncer.cardscan.demo, PID: 19159
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.getbouncer.cardscan.demo/com.getbouncer.cardscan.demo.SingleActivityDemo}: android.view.InflateException: Binary XML file line #69: For input string: "50.0%"
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3114)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: android.view.InflateException: Binary XML file line #69: For input string: "50.0%"
     Caused by: java.lang.NumberFormatException: For input string: "50.0%"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at android.content.res.TypedArray.getFloat(TypedArray.java:424)
        at androidx.constraintlayout.widget.ConstraintLayout$LayoutParams.<init>(ConstraintLayout.java:2771)
        at androidx.constraintlayout.widget.ConstraintLayout.generateLayoutParams(ConstraintLayout.java:1823)
        at androidx.constraintlayout.widget.ConstraintLayout.generateLayoutParams(ConstraintLayout.java:481)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at com.getbouncer.cardscan.demo.SingleActivityDemo.onCreate(SingleActivityDemo.java:111)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

(2)
Process: com.getbouncer.cardscan.demo, PID: 29537
    java.util.IllegalFormatConversionException: d != java.lang.String
        at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4402)
        at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2884)
        at java.util.Formatter$FormatSpecifier.print(Formatter.java:2838)
        at java.util.Formatter.format(Formatter.java:2523)
        at java.util.Formatter.format(Formatter.java:2458)
        at java.lang.String.format(String.java:2883)
        at com.getbouncer.cardscan.demo.SingleActivityDemo.completeScan(SingleActivityDemo.java:390)
        at com.getbouncer.cardscan.demo.SingleActivityDemo.access$100(SingleActivityDemo.java:58)
        at com.getbouncer.cardscan.demo.SingleActivityDemo$1.lambda$onResultBlocking$1$SingleActivityDemo$1(SingleActivityDemo.java:505)
        at com.getbouncer.cardscan.demo.-$$Lambda$SingleActivityDemo$1$YFPpUGpsRB8CgA1-APp2X7xxW-s.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by awushensky** [comment]
Thanks for your report! I'm currently re-writing the UI to be programmatic instead of XML defined so that it can be more easily customized by customers. This appears to be the result of that rewrite.

When I was re-writing the activity UI, I changed these from floats to fractions. I'll revert this.

**Comment by awushensky** [comment]
A fix has been merged to master, and a new release has been cut (version 2.0.0035) with the fix.

I'm planning to do some housekeeping on the single activity demo this week and simplify much of the UI code as well.

**Comment by awushensky** [comment]
I'm closing this issue since the fix was put in place. Please feel free to reopen it if anything else needs to change.
