### ISSUE TITLE
Card scan crash on release

### ISSUE THREAD

**Issue by ornolisvt** [getbouncer/cardscan-android#316]
When generating a release with minifyEnabled and shrinkResources on true. The following error occurs when the card is finished scanning

Fatal Exception: java.lang.RuntimeException: Unknown animation name: x
       at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:216)
       at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:180)
       at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:144)
       at com.getbouncer.scan.ui.util.ViewExtensionsKt.fadeIn(ViewExtensionsKt.java:3)
       at com.getbouncer.cardscan.ui.CardScanBaseActivity$onInterimResult$2.invokeSuspend(CardScanBaseActivity.java:228)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:2)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:70)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

Cannot load an animation. I have searched the library code and it happens on the call to fadeIn ()
`
if (Config.isDebug && result.analyzerResult.ocr?.pan?.isNotEmpty() == true) {
            cardNumberTextView.text = formatPan(result.analyzerResult.ocr.pan)
            cardNumberTextView.show()
        } else {
            val mostLikelyPan = when (val state = result.state) {
                is MainLoopState.Initial -> null
                is MainLoopState.PanFound -> state.getMostLikelyPan()
                is MainLoopState.PanSatisfied -> state.pan
                is MainLoopState.CardSatisfied -> state.getMostLikelyPan()
                is MainLoopState.Finished -> state.pan
            }
            if (mostLikelyPan?.isNotEmpty() == true) {
                cardNumberTextView.text = formatPan(mostLikelyPan)
                cardNumberTextView.fadeIn()
            }
        }
`

**Comment by awushensky** [comment]
I'm able to reproduce this crash.

**Comment by ornolisvt** [comment]
Thank you, please, notify here when it has been corrected

**Comment by awushensky** [comment]
The fix for this crash is deploying now as version `2.0.0072`. ETA 20 minutes.

**Comment by ornolisvt** [comment]
Thanks very much

**Comment by awushensky** [comment]
Release is completed. Thanks for reporting the crash!
