### ISSUE TITLE
"Cannot add a null child view to a ViewGroup" Exception on Camera1Adapter

### ISSUE THREAD

**Issue by francescocervone** [getbouncer/cardscan-android#435]
Version: 2.1.0007

```
Fatal Exception: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
       at android.view.ViewGroup.addView(ViewGroup.java:5021)
       at android.view.ViewGroup.addView(ViewGroup.java:5003)
       at com.getbouncer.scan.camera.Camera1Adapter$onCameraOpen$3.run(Camera1Adapter.java:244)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7094)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by awushensky-stripe** [comment]
Thanks for reporting @francescocervone ! This is a weird one, definitely. let me see if I can reproduce the problem.

**Comment by awushensky-stripe** [comment]
https://github.com/getbouncer/cardscan-android/pull/436
