### ISSUE TITLE
java.lang.RuntimeException: getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by francescocervone** [getbouncer/cardscan-android#448]
Device: Redmi Note 9 Pro
OS version: Android 11
Library version: CardScan 2.1.0010

```
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:2271)
       at com.getbouncer.scan.camera.Camera1Adapter.onPreviewFrame(Camera1Adapter.java:111)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1321)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by awush-stripe** [comment]
This has been released as part of 2.1.0012
