### ISSUE TITLE
failed to build in android studio bumblebee

### ISSUE THREAD

**Issue by dwardy0101** [getbouncer/cardscan-android#494]
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'sonatypeStagingProfileId' for object of type io.github.gradlenexus.publishplugin.NexusRepository.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:88)
	at org.gradle.internal.metaobject.ConfigureDelegate.getProperty(ConfigureDelegate.java:130)
	at build_76cjshiqpqozcifg3g23n78n5$_run_closure5$_closure16$_closure17.doCall(/Users/fdcsam/Desktop/cardscan-android/build.gradle:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
	at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
	at io.github.gradlenexus.publishplugin.DefaultNexusRepositoryContainer$sonatype$2.execute(DefaultNexusRepositoryContainer.kt:38)
	at io.github.gradlenexus.publishplugin.DefaultNexusRepositoryContainer$sonatype$2.execute(DefaultNexusRepositoryContainer.kt:27)
	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:80)
	at io.github.gradlenexus.publishplugin.DefaultNexusRepositoryContainer.create(DefaultNexusRepositoryContainer.kt)
	at io.github.gradlenexus.publishplugin.DefaultNexusRepositoryContainer.sonatype(DefaultNexusRepositoryContainer.kt:35)
	at io.github.gradlenexus.publishplugin.DefaultNexusRepositoryContainer.sonatype(DefaultNexusRepositoryContainer.kt:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:484)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:196)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:56)
	at build_76cjshiqpqozcifg3g23n78n5$_run_closure5$_closure16.doCall(/Users/fdcsam/Desktop/cardscan-android/build.gradle:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
	at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:142)
	at io.github.gradlenexus.publishplugin.DefaultNexusRepositoryContainer.configure(DefaultNexusRepositoryContainer.kt:42)
	at io.github.gradlenexus.publishplugin.DefaultNexusRepositoryContainer.configure(DefaultNexusRepositoryContainer.kt:27)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:103)
	at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
	at io.github.gradlenexus.publishplugin.NexusPublishExtension.repositories(NexusPublishExtension.kt:57)
	at io.github.gradlenexus.publishplugin.NexusPublishExtension_Decorated.repositories(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:484)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:196)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
	at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:34)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:56)
	at build_76cjshiqpqozcifg3g23n78n5$_run_closure5.doCall(/Users/fdcsam/Desktop/cardscan-android/build.gradle:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
	at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
	at org.gradle.internal.extensibility.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:173)
	at org.gradle.internal.extensibility.ExtensionsStorage.configureExtension(ExtensionsStorage.java:64)
	at org.gradle.internal.extensibility.DefaultConvention.configureExtension(DefaultConvention.java:364)
	at org.gradle.internal.extensibility.DefaultConvention.access$500(DefaultConvention.java:45)
	at org.gradle.internal.extensibility.DefaultConvention$ExtensionsDynamicObject.tryInvokeMethod(DefaultConvention.java:301)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
	at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:34)
	at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:135)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:84)
	at build_76cjshiqpqozcifg3g23n78n5.run(/Users/fdcsam/Desktop/cardscan-android/build.gradle:107)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)

**Comment by awush-stripe** [comment]
Hi @dwardy0101 , you can comment out the following line in the associated `build.xml` files:

```
apply from: "deploy.gradle"
```

**Comment by dwardy0101** [comment]
> Hi @dwardy0101 , you can comment out the following line in the associated `build.xml` files:
> 
> ```
> apply from: "deploy.gradle"
> ```

Hello,

I tried removing this and I still get the error. I cant build the app.


```
A problem occurred evaluating root project 'cardscan-android'.
> Could not get unknown property 'sonatypeStagingProfileId' for object of type io.github.gradlenexus.publishplugin.NexusRepository.
```

**Comment by awush-stripe** [comment]
Hi @dwardy0101 ,

Try adding the following lines to your `local.properties` file. These example values should satisfy the missing field requirement.

```
signing.keyId=abc123
signing.password=abc123
signing.secretKeyRingFile=abc123

ossrhUsername=abc123
ossrhPassword=abc123

sonatypeStagingProfileId=abc123
```

**Comment by dwardy0101** [comment]
thanks, @awush-stripe
