### ISSUE TITLE
Crash when intent is null in parseResult callback

### ISSUE THREAD

**Issue by francescocervone** [getbouncer/cardscan-android#506]
Result intent can be null. Library should not always assume that it is always not null.
```
Caused by java.lang.IllegalArgumentException: Required value was null.
       at com.getbouncer.cardscan.ui.CardScanSheet$Companion$activityResultContract$1.parseResult$14e8ec31(CardScanSheet.java:107)
       at com.getbouncer.cardscan.ui.CardScanSheet$Companion$activityResultContract$1.parseResult(CardScanSheet.java:98)
       at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:409)
       at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:366)
       at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:712)
       at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:140)
       at android.app.Activity.dispatchActivityResult(Activity.java:8659)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5857)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5197)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5269)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by awush-stripe** [comment]
Thanks for the report! The fix for this will go out today as part of `2.2.0002`
